In [1]:
import os
import pandas as pd #alias
import numpy as np  #alias
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [2]:
df=pd.read_csv('c:\\Users\\Tenura Pinsara\\Desktop\\ML\\Zuu\\mini_p_00\\Advanced_Telco_Customer_Churn_Prediction\\data\\processed\\Churn_Encoded.csv')
df.head()

,SeniorCitizen,tenure,Contract,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,...,StreamingTV_Yes,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,0,29.85,29.85,No,True,False,False,True,...,False,True,False,False,False,True,False,False,True,False
1,0,34,1,56.95,1889.50,No,False,True,True,False,...,False,True,False,False,True,False,False,False,False,True
2,0,2,0,53.85,108.15,Yes,False,True,True,False,...,False,True,False,False,False,True,False,False,False,True
3,0,45,1,42.30,1840.75,No,False,True,True,False,...,False,True,False,False,True,False,True,False,False,False
4,0,2,0,70.70,151.65,Yes,True,False,True,False,...,False,True,False,False,False,True,False,False,True,False

In [6]:
columns_need_to_be_scaled = ['tenure', 'MonthlyCharges', 'TotalCharges']

for col in columns_need_to_be_scaled:
    scalar = StandardScaler()

    df[col] = scalar.fit_transform(df[col].values.reshape(7043, 1))

df.head()

,SeniorCitizen,tenure,Contract,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,...,StreamingTV_Yes,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,-1.277445,0,-1.160323,-0.994971,No,True,False,False,True,...,False,True,False,False,False,True,False,False,True,False
1,0,0.066327,1,-0.259629,-0.173876,No,False,True,True,False,...,False,True,False,False,True,False,False,False,False,True
2,0,-1.236724,0,-0.362660,-0.960399,Yes,False,True,True,False,...,False,True,False,False,False,True,False,False,False,True
3,0,0.514251,1,-0.746535,-0.195400,No,False,True,True,False,...,False,True,False,False,True,False,True,False,False,False
4,0,-1.236724,0,0.197365,-0.941193,Yes,True,False,True,False,...,False,True,False,False,False,True,False,False,True,False

In [7]:
df.to_csv('c:\\Users\\Tenura Pinsara\\Desktop\\ML\\Zuu\\mini_p_00\\Advanced_Telco_Customer_Churn_Prediction\\data\\processed\\Churn_Final.csv',index=False)